### ISSUE TITLE
Add Kobo downloader too?

### ISSUE THREAD

**Issue by Ansem93** [rmcrackan/AudiobookHub#2]
Hi,
I know that Audible is the most important audiobook store, but can you also add some Kobo tool?
I only know about this one and I still didn't try it:
https://github.com/subdavis/kobo-book-downloader

**Comment by rmcrackan** [comment]
Gladly. Thanks for the link :)

**Comment by rmcrackan** [comment]
Added: https://github.com/rmcrackan/AudiobookHub/blob/master/README.md#non-audible
