### ISSUE TITLE
Libation is no longer windows only

### ISSUE THREAD

**Issue by charltonstanley** [rmcrackan/AudiobookHub#3]
Looking at the releases for the project, there seems to be download for linux and mac.
https://github.com/rmcrackan/Libation/

**Comment by charltonstanley** [comment]
Also, thanks for this awesome resource :smile:

**Comment by rmcrackan** [comment]
> Looking at the releases for the project, there seems to be download for linux and mac.

Yup for over a year now. Jeez -- what idiot keeps up with this stuff anyway??

:) Thanks for pointing that out. Fixed
