### ISSUE TITLE
add audiobookshelf

### ISSUE THREAD

**Issue by michaelsmolka** [rmcrackan/AudiobookHub#4]
Hi, on this list audiobookshelf is definitely missing.

For me it is the perfect solution, together with the great libation app, both running on my NAS.

**Comment by rmcrackan** [comment]
Makes sense. Would you put audiobookshelf under one of the existing categories? Or start a new one?

**Comment by rmcrackan** [comment]
I added a new section for [Listening](https://github.com/rmcrackan/AudiobookHub/blob/master/README.md#listening)

**Comment by michaelsmolka** [comment]
Sorry for my late answer. New section is probably the best. 
thx
